version: "3.9"
services:
  flask:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:
      - python
      - api.py
    ports:
      - ${PORT:-5000}:5000
    environment:
     FLASK_DEBUG: '1'
     FLASK_APP: app
    volumes:
    - ./:/usr/src/app
