version: "3.9"
services:
  flask:
    build:
      args:
        API_ENV: Production
    command:
      - "gunicorn"
      - "-w"
      - "4"
      - "-b"
      - "0.0.0.0:5000"
      - "run:app"
    ports:
    - ${PORT:-5000}:5000
    environment: 
      - API_ENV=Production
