kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # port forward 30000 on the host to 30950 on this node
    extraPortMappings:
      - containerPort: 30950
        hostPort: 30000
        # optional: set the bind address on the host
        # 0.0.0.0 is the current default
        listenAddress: "127.0.0.1"
        # optional: set the protocol to one of TCP, UDP, SCTP.
        # TCP is the default
        protocol: TCP
      - containerPort: 32050
        hostPort: 32000
        listenAddress: "127.0.0.1"
        protocol: TCP
    extraMounts:
      # Modify hostPath to point to your local machine path
      - hostPath: ~/src/currency-converter-sample
        containerPath: /usr/src/app
